### ISSUE TITLE
full scroll

### ISSUE THREAD

**Issue by ArashDev8** [hyperstown/pure-snow.js#7]
hi
how can I do a snow fall with scroll? I mean when I scrolling snow falling continued.

**Comment by hyperstown** [comment]
Hi. By default body tag has `height` set to 100vh and `overflow-y` set to hidden to improve performance. 
You can remove the line `overflow-y: hidden;` that is affecting the `body` tag from the `style.css` file, and change height to desired value.

https://github.com/hyperstown/pure-snow.js/blob/b3bcd4b190887779c4d3c6bc1de022c56d05768e/style.css#L1-L9

If your height is dynamic you would have to re-render snow every time height changes.
You can do re-render snow with this little scirpt:
```js
let styles = document.getElementsByTagName('style');

for (let i = 0; i < styles.length; i++) {
  if (styles[i]?.innerHTML.includes(".snowflake")){
    styles[i].remove();
    document.querySelector("#snow").innerHTML = "";
    createSnow();
    break;
  }
}
```
