### ISSUE TITLE
Invalid HTML attribute count

### ISSUE THREAD

**Issue by designconcepts** [hyperstown/pure-snow.js#8]
First of thank you for your plugin.

The HTML attribute **count** is an invalid HTML attribute. So it would be better to use data-attributes:

`<div id="snow" data-count="200">`

For this the function getSnowAttributes would have to be updated:

`snowWrapper.dataset?.count || snowflakesCount`

Regards, Andreas

**Comment by hyperstown** [comment]
Hi Andreas, great issue, will fix in version 2.1 which should be released soon.
[Additional resources.](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes)

**Comment by hyperstown** [comment]
Sorry for delay, version 2.1 is live on github and should be soon on npm as well.
